
export const listaDeCards = [
  {
    id: 1,
    imagem: "/assets/luffy.png",
    tituloDoproduto: "Action Figure Luffy",
    precoDoProduto: "120",
    descricaoAcess: "Action Figure Luffy",
  },
  {
    id: 2,
    imagem: "/assets/sanji.png",
    tituloDoproduto: "Action Figure Sanji",
    precoDoProduto: "120",
    descricaoAcess: "Action Figure Sanji",
  },
  {
    id: 3,
    imagem: "/assets/zoro.png",
    tituloDoproduto: "Action Figure Zoro",
    precoDoProduto: "120",
    descricaoAcess: "Action Figure Zoro",
  },
  {
    id: 4,
    imagem: "/assets/gameboy.png",
    tituloDoproduto: "Gameboy Clássico - 89",
    precoDoProduto: "450",
    descricaoAcess: "Gameboy Clássico - 89",
  },
  {
    id:5,
    imagem: "/assets/ps5.png",
    tituloDoproduto: "Playstation 5",
    precoDoProduto: "3.690",
    descricaoAcess: "Playstation 5",
  },
  {
    id: 6,
    imagem: "/assets/phone.png",
    tituloDoproduto: "Fone de ouvido sem fio",
    precoDoProduto: "245",
    descricaoAcess: "Fone de ouvido sem fio",
  },
  {
    id: 7,
    imagem: "/assets/mandalorian.png",
    tituloDoproduto: "Action Figure Mandalorian",
    precoDoProduto: "130",
    descricaoAcess: "Action Figure Mandalorian",
  },
  {
    id: 8,
    imagem: "/assets/deadpool.png",
    tituloDoproduto: "Action Figure Deadpool",
    precoDoProduto: "130",
    descricaoAcess: "Action Figure Deadpool",
  },
  {
    id: 9,
    imagem: "/assets/spiderman.png",
    tituloDoproduto: "Action Figure Spider-man",
    precoDoProduto: "130",
    descricaoAcess: "Action Figure spiderman",
  },
];
